version: '3'
services:
  learn-docker:
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
      DATABASES_HOST: db
      DATABASE_PORT: 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgbouncer:
    image: pgbouncer/pgbouncer:1.12.0
    restart: always
    ports:
      - 6432:6432
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db: