version: '3'
services:
  learn-docker:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
  
  pgbouncer:
    image: pgbouncer/pgbouncer:1.12.0
    restart: always
    ports:
      - 6432:6432
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy